#from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'unzip'
        self.ZipMirrorCommand = 'zip'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list1'
        self.SearchCommand = 'search1'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtestt'
        self.CloneCommand = 'clone'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.ZipWatchCommand = 'zipwatch'
        self.QbMirrorCommand = 'qb'
        self.QbUnzipMirrorCommand = 'qbunzip'
        self.QbZipMirrorCommand = 'qbzip'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.LeechSetCommand = 'leechset'
        self.SetThumbCommand = 'setthumb'
        self.LeechCommand = 'leech1'
        self.UnzipLeechCommand = 'unzipleech1'
        self.ZipLeechCommand = 'zipleech1'
        self.QbLeechCommand = 'qbleech1'
        self.QbUnzipLeechCommand = 'qbunzipleech1'
        self.QbZipLeechCommand = 'qbzipleech1'
        self.LeechWatchCommand = 'leechwatch1'
        self.LeechZipWatchCommand = 'leechzipwatch1'
        self.RssListCommand = 'rsslist'
        self.RssGetCommand = 'rssget'
        self.RssSubCommand = 'rsssub'
        self.RssUnSubCommand = 'rssunsub'
        self.RssSettingsCommand = 'rssset'

BotCommands = _BotCommands()
